feat: add shop-screen
Terasology/Economy pull request #22
Opened 2021-07-15 21:35 UTC by ahv15

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/components/PurchasableComponent.java
> +    public int cost = -1;
The default value here is -1, but what does that mean? Does the player get money back when they buy it? And why is -1 a better default value than 0?

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/components/PurchasableComponent.java
> +    public int cost = -1;
And why do we need this at all? This is just a shortcut to avoid having both `Purchasable` and `Value` on an entity, right?

If possible I'd rather have one "marker component" without any fields instead of tracking the same thing in two places.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/events/GiveItemTypeEvent.java
> +public class GiveItemTypeEvent implements Event {
Given that the name is so similar to `GiveItemEvent` I think we should explain the difference between the two here, and also why we need this event in addition.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/events/GiveItemTypeEvent.java
> +    public GiveItemTypeEvent() {
It might be better to make this constructor package private as it is only meant for internal usage for deserialization, but this event does not make much sense with a `null` prefab.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +        if (event.getTargetPrefab() != null) {
That's a safe guard as I would have put it here, but given the r[ecent discussion](https://discord.com/channels/270264625419911192/702893102481932308/868881134807826502) on `World::setBlock` I'm wondering what @keturn would do here?

As this event with a `null` prefab is most likely a bug we should at least log a WARN message if this case occurs.
If we want to be sure that we notice that the case occurred we should probably even throw an exception here. I'm not sure whether we are able to figure out the original sender of the event with an exception here, but I hope that the stacktrace would reveal that information.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +            if (walletAuthoritySystem.isValidTransaction(entity, -item.getComponent(PurchasableComponent.class).cost)) {
Can't we get the component from the prefab even before creating the final entity? If the player cannot purchase an item we should probably not create it.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ui/UIInteractionWrapper.java
> + * Displays a separate widget whilst capturing user interaction with it.
The main use case for this is for tooltips, it seems. Can you explain why this is necessary in more detail?

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ui/ShopScreen.java
> +        wareCost.setText("Cost: " + ShopManager.getWareCost(prefab));
Please add a `//TODO` comment to make this translatable.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ShopManager.java
> +        int cost = ware.getComponent(PurchasableComponent.class).cost;
I'd add a check using Guava preconditions (`checkArgument`)  that `ware` actually is `Purchasable`. Without this check this method will just fail with a NPE.

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ShopManager.java
> +                .collect(Collectors.toSet());
Ah, so all blocks with a `Purchasable` component appear in the shop - that actually sounds reasonable :+1: (at least for the start).

2021-07-26 18:41 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ShopManager.java
> +        }
Why do we do the transaction manually here instead of using the new event?

2021-08-24 20:59 UTC, jdrueckert commented
Do I see it correctly, that this now no longer has a dependency on ST?

2021-08-24 21:30 UTC, ahv15 commented
> Do I see it correctly, that this now no longer has a dependency on ST?

Yup

2021-08-25 07:24 UTC, jdrueckert requested changes
We now have code style annotations in the "Files changed" tab. Please have a look and try to resolve them. Resolving issues in files that your PR doesn't touch is optional (yet appreciated :sweat_smile:)

2021-08-25 07:24 UTC, jdrueckert commented on src/main/java/org/terasology/economy/ShopManager.java
> +    }
Why can we drop the negative costs check that was present here in the GD implementation?

2021-08-25 07:24 UTC, jdrueckert commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +                entity.send(new WalletTransactionEvent(-item.getComponent(ValueComponent.class).value));
Why does the `ItemAuthoritySystem` check the transaction and send the `WalletTransactionEvent` and not the `ShopManager`?

2021-08-25 07:24 UTC, jdrueckert commented on src/main/java/org/terasology/economy/events/GiveItemTypeEvent.java
> + */
I guess the difference to `GiveItem` here is that the item is not actually "moved" but only a copy of it? I think it would help to actively state the difference here, including a cross-reference.

2021-08-25 07:24 UTC, jdrueckert commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +            }
It seems like maybe we could extract some code shared between the prefab and the block case here.

2021-08-25 07:24 UTC, jdrueckert commented on src/main/java/org/terasology/economy/ui/UIInteractionWrapper.java
> + * All size values etc etc are determined by the content widget.
```suggestion
 * All size values etc are determined by the content widget.
```

2021-08-26 12:33 UTC, syntaxi commented on src/main/java/org/terasology/economy/ShopManager.java
> +                .collect(Collectors.toSet());
That is how I designed it in gooey defense in order to save time. I could easily see alternatives used, especially if multiple shops are to be used in parallel. (eg, metal renagades). In this situation, perhaps a URI for each shop which is referenced inside the purchasable component?

2021-08-26 12:35 UTC, syntaxi commented on src/main/java/org/terasology/economy/events/GiveItemTypeEvent.java
> + */
My understanding is that this event is a trigger, to create and then give an item to the player.

2021-08-26 12:58 UTC, syntaxi reviewed
Minor comments and clarifying a question from skaldanar

2021-08-26 12:58 UTC, syntaxi commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +public class ItemAuthoritySystem extends BaseComponentSystem {
I believe that it may be wise to remove this system altogether

Like it was pointed out, it makes more sense for the shop system to check the value, and furthermore I don't see why any of this code has to be done in a separate system.
If we are firing an event, which is only intended to be used for calling this system, then the two should be combined.

2021-08-26 12:58 UTC, syntaxi commented on src/main/java/org/terasology/economy/ui/UIInteractionWrapper.java
> + * Displays a separate widget whilst capturing user interaction with it.
I looked over the prior commits I made and, although I don't recall all the details, it is likely to do with the way user interaction is handled.

We can't just use the `ItemIcon` widget that this contains, because we cannot assign a listener to it
We need to assign a listener to it, because clicking on this widget indicated that this item is selected.
This is visible from the line in ShopScreen#addBlocks
```java
wrapper.setListener(widget -> handleBlockSelected(block));
```
and the line in ShopScreen#addItems
```java
wrapper.setListener(widget -> handlePrefabSelected(item));
```

The listener indicates which shop entry was selected, as well as calling the handler for the specific type, item vs block.

If this is no longer how the code works, and selection is not done by clicking an item in the ship screen, the  this is likely unneeded. However, as far as I am aware, this is not the case and as such, the wrapper is needed.

2021-08-27 05:33 UTC, ahv15 commented on src/main/java/org/terasology/economy/ShopManager.java
> +    }
before if the PurchasableComponent was -1 that meant that the price was stored in the ValueComponent but over here instead we are solely relying on the ValueComponent for the price.

2021-08-27 05:40 UTC, ahv15 commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +public class ItemAuthoritySystem extends BaseComponentSystem {
The main reason for this system is because the GiveItemEvent seems to work mainly on Authoritative Systems and this becomes necessary for multiplayer, and after discussing this with @skaldarnar and @jdrueckert they suggested creating a separate system so that even MR can eventually use this. (MR also makes use of a separate system for this in a similar manner if I am not mistaken)

2021-08-27 05:57 UTC, ahv15 commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +                entity.send(new WalletTransactionEvent(-item.getComponent(ValueComponent.class).value));
Because the ShopManager is not an authoritative system and these checks are better used in Authoritative Systems.

2021-08-28 14:12 UTC, jdrueckert commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +                entity.send(new WalletTransactionEvent(-item.getComponent(ValueComponent.class).value));
Is there a reason, why the ShopManager should stay a non-authoritative system?

2021-08-28 14:21 UTC, jdrueckert commented on src/main/java/org/terasology/economy/ShopManager.java
> +    }
Makes me wonder why we differentiate between the two in the first place and why GD even allows for the price to be in either.

2021-08-28 14:25 UTC, jdrueckert commented on src/main/java/org/terasology/economy/events/GiveItemTypeEvent.java
> + */
Seems like there's some comments that got lost here: I think this documentation still does not clearly distinguish `GiveItemType` from the "normal" `GiveItem`

2021-08-28 14:31 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ShopManager.java
> +    }
I'd assume this has "historical reasons" and our usual reluctance to use and/or modify existing concepts :thinking:

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ShopManager.java
> +        BlockExplorer blockExplorer = new BlockExplorer(assetManager);
code style nitpick: move this closer to where it is used, i.e., after the `purchasableItems` statement.

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/components/PurchasableComponent.java
> +public class PurchasableComponent implements Component<PurchasableComponent> {
```suggestion
public class PurchasableComponent extends EmptyComponent<PurchasableComponent> {
```

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/components/PurchasableComponent.java
> +    }
```suggestion
```

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/handler/CurrencyStorageHandler.java
> +    private final String currency = "currency";
Why change this this way? It looks like it was intended to be a constant value, so just making it static as well would be a better fix?
```suggestion
    private static final String CURRENCY = "currency";
```

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ui/UIInteractionWrapper.java
> + * Displays a separate widget whilst capturing user interaction with it.
Thanks for the explanation!

2021-08-28 14:57 UTC, skaldarnar commented on src/main/java/org/terasology/economy/ui/UIInteractionWrapper.java
> + */
I'd like to add @syntaxi 's explanation (https://github.com/Terasology/Economy/pull/22/files#r696603417) as in-code comment here:

```suggestion
 * All size values etc are determined by the content widget.
 * <p>
 * NOTE: We can't just use the {@code ItemIcon} widget that this contains, because we cannot assign a listener to it.
 * We need to assign a listener to it, because clicking on this widget indicated that this item is selected.
 * This is visible from the line in ShopScreen#addBlocks
 * <pre>
 * wrapper.setListener(widget -> handleBlockSelected(block));
 * </pre>
 * and the line in ShopScreen#addItems
 * <pre>
 * wrapper.setListener(widget -> handlePrefabSelected(item));
 * </pre>
 * The listener indicates which shop entry was selected, as well as calling the handler for the specific type, item vs block.
 */
```

2021-08-28 15:01 UTC, ahv15 commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +                entity.send(new WalletTransactionEvent(-item.getComponent(ValueComponent.class).value));
This is so that the ShopScreen which is accessible by all players can access the ShopManager.

2021-08-28 15:04 UTC, ahv15 commented on src/main/java/org/terasology/economy/handler/CurrencyStorageHandler.java
> +    private final String currency = "currency";
I was trying to resolve some of the suggestions given.

2021-08-28 17:37 UTC, skaldarnar commented on src/main/java/org/terasology/economy/systems/ItemAuthoritySystem.java
> +public class ItemAuthoritySystem extends BaseComponentSystem {
I tried to integrate that (as authority event handler) into the `ShopManager` in 969e482

2021-10-09 19:05 UTC, jdrueckert approved these changes

2021-10-09 19:13 UTC, merged